// <auto-generated />
namespace POS.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update05122020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update05122020));
        
        string IMigrationMetadata.Id
        {
            get { return "202005120637479_update-05-12-2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
