// <auto-generated />
namespace POS.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_3122020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_3122020));
        
        string IMigrationMetadata.Id
        {
            get { return "202003120441382_update_3122020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
