// <auto-generated />
namespace POS.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PosTransaction_IsComplete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PosTransaction_IsComplete));
        
        string IMigrationMetadata.Id
        {
            get { return "202001261012477_PosTransaction_IsComplete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
